### ISSUE TITLE
Missing run_noiseCalc.sh

### ISSUE THREAD

**Issue by zoonono** [mrirecon/ring#1]
Hello, very nice work! Thanks a lot for sharing!
I met problems when I run SupFig1/SheppLogan/run.sh, SupFig1/Geo1/run.sh, SupFig1/Geo2/run.sh.
./run.sh: line 15: cd: noise: No such file or directory
It seems that there is no directory called "noise", and there is no "run_noiseCalc.sh".
Could you please upload these files and directories to GitHub? Thanks a lot!

**Comment by hcmh** [comment]
Hey, I have just pushed a commit that (re)-adds the missing scripts. 

For using them, you will have to compile a special version of bart:

1. Make sure that you are using a commit later than the reference commit given in the README.md, but earlier than `480509c417`
2. In the bart repository, create a file Makefiles/Makefile.local with the contents: `CPPFLAGS+=-DRING_PAPER`
3. And then compile bart

This causes bart to output internal data needed for SupFig1. (More specifically, it causes bart to write to the files `projangle.txt` 
and `offset.txt` on each call to `bart estdelay`.)

Does this fix your problem?

**Comment by zoonono** [comment]
Thank you so much for your detailed explanation! My problem has been solved smoothly. Thanks!

**Comment by hcmh** [comment]
Sure, no problem! Thanks for alerting us to the problem.
